name: flutter_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.1
  provider: ^6.1.2
  dio: ^5.5.0+1
  intl: ^0.19.0
  pubspec_parse: ^1.3.0
  package_info_plus: ^8.0.1
  url_launcher: ^6.3.0
  icons_plus: ^5.0.0
  logging: ^1.2.0
  get_it: ^7.7.0
  bot_toast: ^4.1.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  json_model: ^1.0.0
  intl_generator: ^0.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - imgs/