name: flutter_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  dio: ^5.6.0
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  icons_plus: ^5.0.0
  logging: ^1.2.0
  get_it: ^7.7.0
  bot_toast: ^4.1.3
  flutter_svg: ^2.0.10+1
  random_avatar: ^0.0.8
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  json_model: ^1.0.0
  intl_generator: ^0.4.1

flutter:
  uses-material-design: true
  assets:
    - imgs/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Italic.ttf
          style: italic